language: python

python:
  - "2.6"
  - "2.7"

env:
    - DJANGO_VERSION=1.6.5
    - DJANGO_VERSION=1.4.5
    - DJANGO_VERSION=1.5

install: 
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -r .travis-requirements.txt --use-mirrors

script:
    - django-admin.py test --settings='tests.test_settings' --pythonpath=$PWD
