language: python

python:
  - "2.6"
  - "2.7"

install: 
  - "pip install -r requirements.txt --use-mirrors"

script:
    - django-admin.py test --settings='tests.test_settings' --pythonpath=$PWD --with-coverage --cover-package=domande

